import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  MapPin,
  Sparkles,
  HeartHandshake,
  BarChart3,
  Clock,
  Zap,
} from "lucide-react";

export default function Home() {
  return (
    <div className="w-full">
      {/* Hero Section */}
      <section className="w-full bg-linear-to-br from-blue-600 via-blue-500 to-blue-700 text-white py-20">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <h1 className="text-5xl md:text-6xl font-bold mb-6">
            Your Weekend, Planned in Minutes
          </h1>
          <p className="text-xl md:text-2xl mb-8 text-blue-100">
            AI-powered discovery and planning for unforgettable experiences in
            Cambodia
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <Link href="/explore">
              <Button
                size="lg"
                className="bg-white text-blue-600 hover:bg-gray-100"
              >
                Start Exploring
              </Button>
            </Link>
            <Link href="/signup">
              <Button
                size="lg"
                variant="outline"
                className="border-white text-white hover:bg-blue-700"
              >
                Sign Up Now
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="max-w-7xl mx-auto px-4 py-16">
        <h2 className="text-3xl font-bold text-center mb-12">
          Why LocalExplore?
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <Card>
            <CardHeader>
              <Sparkles className="w-10 h-10 text-blue-600 mb-2" />
              <CardTitle>AI-Powered Plans</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">
                Get personalized itineraries generated by AI based on your
                preferences, budget, and mood
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <MapPin className="w-10 h-10 text-blue-600 mb-2" />
              <CardTitle>Curated Spots</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">
                Discover handpicked cafés, restaurants, shops, and attractions
                recommended by locals
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <Clock className="w-10 h-10 text-blue-600 mb-2" />
              <CardTitle>Save Time</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-gray-600">
                Skip the planning stress and spend more time enjoying authentic
                experiences
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* User Types Section */}
      <section className="bg-gray-50 py-16">
        <div className="max-w-7xl mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">For Everyone</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Explorers */}
            <Card className="hover:shadow-lg transition-shadow">
              <CardHeader>
                <Zap className="w-10 h-10 text-green-600 mb-2" />
                <CardTitle>For Explorers</CardTitle>
                <CardDescription>Discover & Plan</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <p className="text-sm text-gray-600">
                  ✓ Personalized itineraries
                </p>
                <p className="text-sm text-gray-600">✓ Bucket list features</p>
                <p className="text-sm text-gray-600">✓ Save favorite spots</p>
                <Link href="/explore">
                  <Button className="w-full mt-4">Explore Now</Button>
                </Link>
              </CardContent>
            </Card>

            {/* Partners */}
            <Card className="hover:shadow-lg transition-shadow">
              <CardHeader>
                <HeartHandshake className="w-10 h-10 text-orange-600 mb-2" />
                <CardTitle>For Partners</CardTitle>
                <CardDescription>Grow Your Business</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <p className="text-sm text-gray-600">✓ Promote your business</p>
                <p className="text-sm text-gray-600">✓ View analytics</p>
                <p className="text-sm text-gray-600">✓ Manage subscriptions</p>
                <Link href="/partner/signup">
                  <Button className="w-full mt-4" variant="outline">
                    Join as Partner
                  </Button>
                </Link>
              </CardContent>
            </Card>

            {/* Admins */}
            <Card className="hover:shadow-lg transition-shadow">
              <CardHeader>
                <BarChart3 className="w-10 h-10 text-purple-600 mb-2" />
                <CardTitle>For Admins</CardTitle>
                <CardDescription>Manage Platform</CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <p className="text-sm text-gray-600">✓ Platform analytics</p>
                <p className="text-sm text-gray-600">✓ User management</p>
                <p className="text-sm text-gray-600">✓ Content moderation</p>
                <Button className="w-full mt-4" variant="outline" disabled>
                  Admin Portal
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="max-w-7xl mx-auto px-4 py-16 text-center">
        <h2 className="text-3xl font-bold mb-6">Ready to Explore?</h2>
        <p className="text-lg text-gray-600 mb-8">
          Join thousands of explorers discovering the best of Cambodia
        </p>
        <Link href="/signup">
          <Button size="lg" className="bg-blue-600 hover:bg-blue-700">
            Get Started Today
          </Button>
        </Link>
      </section>
    </div>
  );
}
